### PR TITLE
Add malloc cheat sheet

### PR DESCRIPTION
**Pull request by eegli**

### CODE REVIEW

**Comment by qingchen3** [comment]
@eegli  Thanks very much for your contribution. There might be some changes on top of your initial commit, because some others might also contribute to it, and we might also modify the content based on the course. I will let you know if there are changes. 

Do you mind that I put your name and/or your webpage link in a new "acknowledge" section that list all contributors?

**Comment by eegli** [comment]
Sure, feel free to fact check and/or modify to fit the current cheat sheet style.

**Comment by qingchen3** [comment]
@eegli We will add an acknowledge section that thanks all contributors, do you mind that your name is added there?

**Comment by eegli** [comment]
Not at all, go ahead!

**Pull request merged**
